name: Auto Label Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Add Labels to Issues
      if: github.event_name == 'issues'
      uses: actions-ecosystem/action-add-labels@v1.1.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: |
          gssoc
          level1
