name: Auto Label Issues and PRs

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Add Label to Issues
      if: github.event_name == 'issues'
      uses: actions-ecosystem/action-add-labels@v1.1.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: gssoc

    - name: Add Label to Pull Requests
      if: github.event_name == 'pull_request'
      uses: actions-ecosystem/action-add-labels@v1.1.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: gssoc